services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpm_frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - mpm_network

networks:
  mpm_network:
    external: true